services:
  nginx:
    image: ghcr.io/xlance-collective/npower-protal:prd-latest
    container_name: vue-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/keys:/etc/nginx/keys
      - static_volume:/home/app/web/staticfiles

    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    networks:
      - app-network

  django:
    image: ghcr.io/xlance-collective/npower-backend:latest
    container_name: django-dev
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - redis
    expose:
      - 8000
    env_file:
      - ./.env.be
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis/redis-stack-server:7.4.0-v5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  static_volume:
  redis_data:
