services:
  nginx:
    image: ghcr.io/xlance-collective/npower-protal:prd-latest
    container_name: vue-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/keys:/etc/nginx/keys
      - static_volume:/home/app/web/staticfiles

    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
      - flask-dev
    networks:
      - app-network

  django:
    image: ghcr.io/xlance-collective/npower-backend:latest
    container_name: django-dev
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./gemini-cred.json:/home/app/web/gemini-cred.json
      - ./firebase-cred.json:/home/app/web/firebase-cred.json
    depends_on:
      - redis
    expose:
      - 8000
    env_file:
      - ./.env.be
    networks:
      - app-network

  celery:
    image: ghcr.io/xlance-collective/npower-backend:latest
    container_name: celery
    command: celery -A configs worker -l info
    volumes:
      - ./gemini-cred.json:/home/app/web/gemini-cred.json
      - ./firebase-cred.json:/home/app/web/firebase-cred.json
    depends_on:
      - redis
    env_file:
      - ./.env.be
    networks:
      - app-network

  beat:
    image: ghcr.io/xlance-collective/npower-backend:latest
    container_name: beat
    command: celery -A configs beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./gemini-cred.json:/home/app/web/gemini-cred.json
      - ./firebase-cred.json:/home/app/web/firebase-cred.json
    depends_on:
      - redis
    env_file:
      - ./.env.be
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis/redis-stack-server:7.4.0-v5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  flask-dev:
    image: ghcr.io/xlance-collective/flask-dev:latest
    container_name: flask-dev
    command: python server.py
    env_file:
      - .env.fk
    depends_on:
      - chromadb
    ports:
      - "5000:5000"
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - app-network


  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: on-failure
    env_file:
      - .env.fk
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  static_volume:
  redis_data:
  chromadb_data:
