name: Deploy UAT Files to Server
on:
  push:
    branches:
      - uat
jobs:
  deploy:
    runs-on: np-dev-op

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy uat/ to app/ folder on server
      run: |
        rsync -avz uat/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/username/app/
