name: Deploy UAT Files to Server
on:
  push:
    branches:
      - "main"

env:
  SSH_USERNAME: ${{ vars.SSH_USERNAME }}
  SSH_HOST: ${{ vars.SSH_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  CR_PAT: ${{ secrets.CR_PAT }}
  ENV_BE: ${{ secrets.ENV_BE }}
  ENV_WP: ${{ secrets.ENV_WP }}
  ENV_FK: ${{ secrets.ENV_FK }}

jobs:
  copy:
    runs-on: np-dev-op

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/uat.pem
          chmod 600 ~/.ssh/uat.pem

          echo "$SSH_HOST" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Upload .env files to server
        run: |
          ssh -i ~/.ssh/uat.pem -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOST" "
            mkdir -p /home/$SSH_USERNAME/app &&
            echo '$ENV_BE' > /home/$SSH_USERNAME/app/.env.be &&
            echo '$ENV_WP' > /home/$SSH_USERNAME/app/.env.wp
            echo '$ENV_FK' > /home/$SSH_USERNAME/app/.env.fk
          "

      - name: Copy uat/ excluding nginx to app/ folder on server
        run: |
          rsync -rlptDz \
                  --exclude 'nginx/' \
                  --exclude '**/*.example.env.*' \
                  -e "ssh -i ~/.ssh/uat.pem -o StrictHostKeyChecking=no" \
                  uat/  "$SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME/app/"

      - name: Copy nginx folder to server
        run: |
          ssh -i ~/.ssh/uat.pem -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "mkdir -p /home/$SSH_USERNAME/app/nginx && sudo chown $SSH_USERNAME:$SSH_USERNAME /home/$SSH_USERNAME/app/nginx && sudo chmod ug+w /home/$SSH_USERNAME/app/nginx"
          rsync -az uat/nginx/ $SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME/app/nginx/

  deploy:
    runs-on: np-dev-op
    needs: copy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/uat.pem
          chmod 600 ~/.ssh/uat.pem

          echo "$SSH_HOST" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Run deploy script
        run: |
          ssh -i ~/.ssh/uat.pem -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_HOST" << EOF
            cd ~/app
            export $(cat .env.be | xargs)
            export $(cat .env.wp | xargs)
            export $(cat .env.fk | xargs)
            echo "$CR_PAT" | docker login ghcr.io -u "$SSH_USERNAME" --password-stdin
            docker compose pull --quiet
            docker compose down
            docker compose up -d
            docker compose exec django python manage.py migrate --noinput
            docker system prune -a -f
            docker logout
          EOF
