name: Deploy UAT Files to Server
on:
  push:
    tags:
      - "prd-*"

jobs:
  copy:
    runs-on: np-dev-op
    env:
      SSH_USERNAME: ${{ vars.SSH_PRD_USERNAME }}
      SSH_HOST: ${{ vars.SSH_PRD_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRD_PRIVATE_KEY }}
      ENV_BE: ${{ secrets.ENV_PRD_BE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Upload .env files to server
        run: |
          ssh "$SSH_USERNAME@$SSH_HOST" "
            mkdir -p /home/$SSH_USERNAME/app &&
            echo '$ENV_BE' > /home/$SSH_USERNAME/app/.env.be &&
          "

      - name: Copy prd/ excluding nginx to app/ folder on server
        run: |
          rsync -rlptDz --exclude 'nginx/' --exclude '**/*.example.env.*' prd/ $SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME/app/

      - name: Copy nginx folder to server
        run: |
          ssh $SSH_USERNAME@$SSH_HOST "mkdir -p /home/$SSH_USERNAME/app/nginx && sudo chown $SSH_USERNAME:$SSH_USERNAME /home/$SSH_USERNAME/app/nginx && sudo chmod ug+w /home/$SSH_USERNAME/app/nginx"
          rsync -az prd/nginx/ $SSH_USERNAME@$SSH_HOST:/home/$SSH_USERNAME/app/nginx/

  deploy:
    runs-on: np-dev-op
    needs: copy
    env:
      SSH_USERNAME: ${{ vars.SSH_PRD_USERNAME }}
      SSH_HOST: ${{ vars.SSH_PRD_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRD_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Run Server
        run: |
          ssh -t $SSH_USERNAME@$SSH_HOST << 'ENDSSH'
            cd ~/app
            export $(cat .env.be | xargs)
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u USERNAME --password-stdin
            docker compose pull --quiet
            docker compose down
            docker compose up -d
            docker compose exec django python manage.py migrate --noinput
            docker image prune -af
            docker logout
          ENDSSH
